## Sam Dennon // 11MAY2023 ##

ARG BALENA_ARCH=%%BALENA_ARCH%%

FROM balenalib/$BALENA_ARCH-debian-python
WORKDIR /usr/src/lazy
RUN install_packages nano htop
COPY entry.sh .
ENTRYPOINT [ "/bin/bash", "/usr/src/lazy/entry.sh"]